name: Build Flatpak Bundle
on:
  workflow_dispatch:
    inputs:
      release-tag:
        description: 'Tag to build (e.g., v1.0.0)'
        required: true
        type: string

jobs:
  build-flatpak:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Flatpak Manifest
        uses: actions/checkout@v4
        with:
          repository: arc360alt/com.arkrith.ArkRinth
          path: flatpak-manifest

      - name: Install Flatpak and Builder
        run: |
          sudo apt-get update
          sudo apt-get install -y flatpak flatpak-builder
          flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

      - name: Install Required Runtimes
        run: |
          flatpak install -y flathub org.gnome.Platform//45 org.gnome.Sdk//45
          flatpak install -y flathub org.freedesktop.Sdk.Extension.rust-stable//23.08
          flatpak install -y flathub org.freedesktop.Sdk.Extension.node18//23.08

      - name: Build with Flatpak Builder
        run: |
          flatpak-builder \
          --force-clean \
          --repo=repo \
          --install-deps-from=flathub \
          build-dir \
          flatpak-manifest/com.arkrith.ArkRinth.yml

      - name: Create Bundle
        run: |
          flatpak build-bundle repo com.arkrith.ArkRinth.flatpak com.arkrith.ArkRinth

      - name: Upload Flatpak Bundle
        uses: actions/upload-artifact@v4
        with:
          name: ArkRinth-Flatpak-${{ github.event.inputs.release-tag }}
          path: com.arkrith.ArkRinth.flatpak
