name: Build Flatpak Bundle
on:
  workflow_dispatch:
    inputs:
      release-tag:
        description: 'Tag to build (e.g., v1.0.0)'
        required: true
        type: string

jobs:
  build-flatpak:
    runs-on: ubuntu-latest
    timeout-minutes: 30  # Prevent early timeout
    
    steps:
    - name: Checkout Flatpak Manifest
      uses: actions/checkout@v4
      with:
        repository: arc360alt/com.arkrith.ArkRinth
        path: flatpak-manifest

    - name: Install System Dependencies
      run: |
        sudo apt-get update
        # Install ONLY flatpak and flatpak-builder first
        sudo apt-get install -y flatpak flatpak-builder
        echo "Flatpak installed successfully"

    - name: Setup Flatpak Repository
      run: |
        flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
        echo "Flathub repository added"

    - name: Install Runtimes (with retry logic)
      run: |
        # Install runtimes one by one with retries
        max_retries=3
        retry_count=0
        
        until flatpak install -y flathub org.gnome.Platform//45 org.gnome.Sdk//45 || [ $retry_count -eq $max_retries ]
        do
            retry_count=$((retry_count+1))
            echo "Attempt $retry_count failed, retrying in 5 seconds..."
            sleep 5
        done
        
        if [ $retry_count -eq $max_retries ]; then
            echo "Failed to install GNOME runtime after $max_retries attempts"
            exit 1
        fi

        # Install extensions
        flatpak install -y flathub org.freedesktop.Sdk.Extension.rust-stable//23.08
        flatpak install -y flathub org.freedesktop.Sdk.Extension.node18//23.08
        echo "All runtimes installed successfully"

    - name: Verify Flatpak Installation
      run: |
        flatpak --version
        flatpak-builder --version
        flatpak list
        echo "Verification complete"

    - name: Build with Flatpak Builder
      run: |
        cd flatpak-manifest
        flatpak-builder \
          --verbose \
          --force-clean \
          --repo=repo \
          --install-deps-from=flathub \
          ../build-dir \
          com.arkrith.ArkRinth.yml

    - name: Create Bundle
      run: |
        flatpak build-bundle repo com.arkrith.ArkRinth.flatpak com.arkrith.ArkRinth

    - name: Upload Flatpak Bundle
      uses: actions/upload-artifact@v4
      with:
        name: ArkRinth-Flatpak-${{ github.event.inputs.release-tag }}
        path: com.arkrith.ArkRinth.flatpak
