name: Build Flatpak Bundle
on:
  workflow_dispatch:
    inputs:
      release-tag:
        description: 'Tag to build (e.g., v1.0.0)'
        required: true
        type: string

jobs:
  build-flatpak:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - name: Checkout Flatpak Manifest
      uses: actions/checkout@v4
      with:
        repository: arc360alt/com.arkrith.ArkRinth
        path: flatpak-manifest

    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y flatpak flatpak-builder
        echo "Flatpak installed successfully"

    - name: Setup Flatpak User Repository
      run: |
        # Use --user flag for user-level installation
        flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
        echo "Flathub repository added to user space"

    - name: Install Runtimes (User Space)
      run: |
        # Install everything to user space with --user flag
        flatpak install --user -y flathub org.gnome.Platform//45 org.gnome.Sdk//45
        flatpak install --user -y flathub org.freedesktop.Sdk.Extension.rust-stable//23.08
        flatpak install --user -y flathub org.freedesktop.Sdk.Extension.node18//23.08
        echo "All runtimes installed to user space"

    - name: Verify Flatpak Installation
      run: |
        flatpak --version
        flatpak-builder --version
        flatpak list --user
        echo "Verification complete"

    - name: Build with Flatpak Builder
      run: |
        cd flatpak-manifest
        # Tell flatpak-builder to use user installations
        XDG_DATA_DIRS="/home/runner/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:$XDG_DATA_DIRS" \
        flatpak-builder \
          --verbose \
          --force-clean \
          --repo=repo \
          --install-deps-from=flathub \
          ../build-dir \
          com.arkrith.ArkRinth.yml

    - name: Create Bundle
      run: |
        flatpak build-bundle repo com.arkrith.ArkRinth.flatpak com.arkrith.ArkRinth

    - name: Upload Flatpak Bundle
      uses: actions/upload-artifact@v4
      with:
        name: ArkRinth-Flatpak-${{ github.event.inputs.release-tag }}
        path: com.arkrith.ArkRinth.flatpak
